import { BaseEntity, Column, DB, Entity, EntityQuery, HasMany, Scope, SqliteDataSource } from '../src'

/**
 * Global scopes inside whereHas/orWhereHas subqueries.
 *
 * A global scope states an invariant about an entity — "a soft-deleted post
 * does not exist", "a tournament of another organization does not exist" — so a
 * relation constraint has to honour it the same way a direct query does, and
 * the same way `with()` already does when it eager-loads that relation.
 * Otherwise `whereHas('posts')` quietly stops meaning "has posts" and starts
 * meaning "has a row in the posts table", which is how a multi-tenant filter or
 * a soft delete gets bypassed without an error anywhere.
 *
 * whereHas is a synchronous chainable and a scope may be asynchronous, so the
 * subquery cannot be scoped where it is built: EntityQuery registers it as
 * pending and resolves it from the terminal method (see
 * _resolvePendingRelationQueries).
 */

/** Only published posts exist, as far as the application is concerned. */
class PublishedScope implements Scope {
  apply(query: EntityQuery<any>): void {
    query.where('published', true)
  }
}

/** An asynchronous scope — the case that forced the deferred resolution. */
class AsyncPublishedScope implements Scope {
  async apply(query: EntityQuery<any>): Promise<void> {
    await Promise.resolve()
    query.where('published', true)
  }
}

@Entity({ table: 'posts' })
class Post extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  authorId!: number

  @Column()
  title!: string

  @Column({ cast: 'boolean' })
  published!: boolean

  protected static booted(): void {
    Post.addGlobalScope(new PublishedScope())
  }
}

@Entity({ table: 'posts' })
class AsyncPost extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  authorId!: number

  @Column()
  title!: string

  @Column({ cast: 'boolean' })
  published!: boolean

  protected static booted(): void {
    AsyncPost.addGlobalScope(new AsyncPublishedScope())
  }
}

@Entity({ table: 'authors' })
class Author extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @HasMany(() => Post, 'authorId')
  posts?: Post[]

  @HasMany(() => AsyncPost, 'authorId')
  asyncPosts?: AsyncPost[]
}

describe('Global scopes inside whereHas', () => {
  let source: SqliteDataSource

  beforeAll(async () => {
    source = new SqliteDataSource()

    await source.execute(`
      CREATE TABLE authors (
        id   INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL
      )
    `)
    await source.execute(`
      CREATE TABLE posts (
        id        INTEGER PRIMARY KEY AUTOINCREMENT,
        authorId  INTEGER NOT NULL,
        title     TEXT    NOT NULL,
        published INTEGER NOT NULL DEFAULT 1
      )
    `)

    DB.register(source)
  })

  afterAll(async () => {
    await source.close()
  })

  beforeEach(async () => {
    await source.execute('DELETE FROM posts')
    await source.execute('DELETE FROM authors')
    // Alice has a published post, Bob only an unpublished one, Carol none.
    await source.execute(`INSERT INTO authors (id, name) VALUES (1, 'Alice'), (2, 'Bob'), (3, 'Carol')`)
    await source.execute(
      `INSERT INTO posts (authorId, title, published) VALUES (1, 'Alice published', 1), (1, 'Alice draft', 0), (2, 'Bob draft', 0)`
    )
  })

  it('applies the related entity scope when the callback is omitted', async () => {
    const authors = await Author.whereHas('posts').get()

    // Bob's only post is unpublished: as far as the application is concerned he
    // has no posts at all.
    expect(authors.map((author) => author.name)).toEqual(['Alice'])
  })

  it('applies it alongside the conditions the callback adds', async () => {
    const withDraftTitle = await Author.whereHas('posts', (query) => query.whereLike('title', '%draft%')).get()

    // Alice's draft is unpublished and Bob's only post is too, so the scope and
    // the callback together match nobody — the callback alone would match both.
    expect(withDraftTitle).toEqual([])
  })

  it('awaits an asynchronous scope', async () => {
    const authors = await Author.whereHas('asyncPosts').get()

    expect(authors.map((author) => author.name)).toEqual(['Alice'])
  })

  it('lets the callback opt out by name', async () => {
    const authors = await Author.whereHas('posts', (query) => query.withoutGlobalScope('PublishedScope')).get()

    expect(authors.map((author) => author.name).sort()).toEqual(['Alice', 'Bob'])
  })

  it('lets the callback opt out of every scope', async () => {
    const authors = await Author.whereHas('posts', (query) => query.withoutGlobalScopes()).get()

    expect(authors.map((author) => author.name).sort()).toEqual(['Alice', 'Bob'])
  })

  it('keeps the correlated condition AND-ed with an orWhere inside the callback', async () => {
    // Without the nested group the OR would swallow the correlation and match
    // every author. The scope is dropped so only the precedence is under test.
    const authors = await Author.whereHas('posts', (query) =>
      query.withoutGlobalScopes().where('title', 'Alice published').orWhere('title', 'Bob draft')
    ).get()

    expect(authors.map((author) => author.name).sort()).toEqual(['Alice', 'Bob'])
  })

  it('scopes an orWhereHas subquery too', async () => {
    const authors = await Author.where('name', 'Carol').orWhereHas('posts').get()

    expect(authors.map((author) => author.name).sort()).toEqual(['Alice', 'Carol'])
  })

  it('agrees with what with() eager-loads for the same relation', async () => {
    const authors = await Author.whereHas('posts').with('posts').get()

    // The two ways of reaching the relation have to describe the same set —
    // this is the asymmetry the change fixes. Before it, whereHas matched Bob
    // (he has a row in posts) while with() then eager-loaded nothing for him,
    // so the same query said both that he has posts and that he has none.
    expect(authors.map((author) => author.name)).toEqual(['Alice'])
    expect(authors.every((author) => (author.posts?.length ?? 0) > 0)).toBe(true)
    expect(authors[0]!.posts?.map((post) => post.title)).toEqual(['Alice published'])
  })
})
